# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('account', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('auth_parents', models.CharField(max_length=1)),
                ('auth_bonne', models.CharField(max_length=1)),
                ('auth_daycarecenter', models.CharField(max_length=1)),
            ],
        ),
    ]
