# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baby_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_bonne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('seniority', models.CharField(blank=True, max_length=3, null=True)),
                ('specialty', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('baby_count_record', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_daycarecenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('setuptime', models.DateField(blank=True, null=True)),
                ('business_philosophy', models.TextField(blank=True, null=True)),
                ('diet_plan', models.TextField(blank=True, null=True)),
                ('learn_plan', models.TextField(blank=True, null=True)),
                ('about_us', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_normal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('tips', models.TextField(blank=True, null=True)),
                ('img', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='user_normal',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby_user.user'),
        ),
        migrations.AddField(
            model_name='user_daycarecenter',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby_user.user'),
        ),
        migrations.AddField(
            model_name='user_bonne',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby_user.user'),
        ),
    ]
