# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baby_user', '0002_auto_20160309_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_bonne',
            name='user_id_daycarecenter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baby_user.user_daycarecenter'),
            preserve_default=False,
        ),
    ]
