# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_user', '0004_auto_20160309_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_bonne',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_bonne',
            name='user_id_daycarecenter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_daycarecenter',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_normal',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
