# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 06:05
from __future__ import unicode_literals

import baby_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_user', '0005_auto_20160313_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_normal',
            name='user_id',
            field=models.IntegerField(verbose_name=baby_user.models.user),
        ),
    ]
