# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_user', '0006_auto_20160313_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user_normal',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
