# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_user', '0007_auto_20160313_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_bonne',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_daycarecenter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_parents',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_bonne',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user_daycarecenter',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user_normal',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
