# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_user', '0015_auto_20160317_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_bonne',
            name='baby_count_record',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user_bonne',
            name='experience',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user_bonne',
            name='seniority',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user_bonne',
            name='specialty',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user_daycarecenter',
            name='about_us',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user_daycarecenter',
            name='business_philosophy',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user_daycarecenter',
            name='diet_plan',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user_daycarecenter',
            name='learn_plan',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user_daycarecenter',
            name='setuptime',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user_normal',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user_normal',
            name='birthday',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user_normal',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user_normal',
            name='name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_normal',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_normal',
            name='sex',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user_normal',
            name='tips',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
