# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_user', '0016_auto_20160404_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_daycarecenter',
            name='setuptime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_normal',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
