# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_user', '0019_auto_20160406_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_bonne',
            name='baby_count_record',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
