# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 13:53
from __future__ import unicode_literals

import baby_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_user', '0020_auto_20160406_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='header_pic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(blank=True, upload_to=baby_user.models.PathAndRename('image/header_pic/'))),
            ],
        ),
    ]
