# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby_user', '0023_auto_20160424_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_bonne',
            old_name='baby_auth_count',
            new_name='baby_auth',
        ),
        migrations.RenameField(
            model_name='user_daycarecenter',
            old_name='baby_auth_count',
            new_name='baby_auth',
        ),
    ]
