# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baby_user', '0004_auto_20160309_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification_apns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('useragent', models.CharField(max_length=100)),
                ('deviceid', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby_user.user')),
            ],
        ),
        migrations.CreateModel(
            name='notification_gcm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('useragent', models.CharField(max_length=100)),
                ('deviceid', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby_user.user')),
            ],
        ),
    ]
