# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_apns',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='notification_gcm',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
