# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20160315_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification_gcm',
            name='deviceid',
        ),
        migrations.RemoveField(
            model_name='notification_gcm',
            name='useragent',
        ),
        migrations.AddField(
            model_name='notification_gcm',
            name='token',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
