# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0002_produce_trade_allpay_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='produce_type_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produce_trade',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
