# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_auto_20160317_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center_picture',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='center_visit',
            name='user_id_daycarecenter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
