# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baby_user', '0004_auto_20160309_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='discuss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='discuss_message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('discuss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discuss.discuss')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby_user.user')),
            ],
        ),
        migrations.CreateModel(
            name='discuss_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='discuss',
            name='discuss_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discuss.discuss_type'),
        ),
        migrations.AddField(
            model_name='discuss',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby_user.user'),
        ),
    ]
