# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baby_user', '0004_auto_20160309_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='baby',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('tips', models.TextField(blank=True, null=True)),
                ('img', models.URLField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('nickname', models.CharField(max_length=20)),
                ('user_id', models.IntegerField()),
                ('user_id_father', models.IntegerField()),
                ('user_id_mother', models.IntegerField()),
                ('user_id_bonne', models.IntegerField()),
                ('user_id_daycarecenter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='baby_barcode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('identify', models.CharField(blank=True, max_length=1, null=True)),
                ('baby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby.baby')),
            ],
        ),
        migrations.CreateModel(
            name='baby_breastfeeding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(blank=True, max_length=30, null=True)),
                ('baby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby.baby')),
            ],
        ),
        migrations.CreateModel(
            name='baby_chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('identify', models.CharField(blank=True, max_length=1, null=True)),
                ('message', models.CharField(max_length=500)),
                ('baby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby.baby')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby_user.user')),
            ],
        ),
        migrations.CreateModel(
            name='baby_defecation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(blank=True, max_length=30, null=True)),
                ('baby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby.baby')),
            ],
        ),
        migrations.CreateModel(
            name='baby_dessertfruit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(blank=True, max_length=30, null=True)),
                ('baby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby.baby')),
            ],
        ),
        migrations.CreateModel(
            name='baby_diaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(blank=True, max_length=30, null=True)),
                ('baby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby.baby')),
            ],
        ),
        migrations.CreateModel(
            name='baby_grocery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(blank=True, max_length=30, null=True)),
                ('baby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby.baby')),
            ],
        ),
        migrations.CreateModel(
            name='baby_picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('img', models.URLField(blank=True, null=True)),
                ('baby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby.baby')),
            ],
        ),
        migrations.CreateModel(
            name='baby_relatives',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('baby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby.baby')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby_user.user')),
            ],
        ),
    ]
