# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 17:20
from __future__ import unicode_literals

import baby_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='baby',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=20)),
                ('birthday', models.DateField(null=True)),
                ('sex', models.CharField(blank=True, default=0, max_length=2, null=True)),
                ('tips', models.TextField(blank=True, default='', null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=baby_user.models.PathAndRename('image/baby/'))),
                ('height', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('weight', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('nickname', models.CharField(blank=True, default='', max_length=20)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_id_father', models.IntegerField(blank=True, null=True)),
                ('user_id_mother', models.IntegerField(blank=True, null=True)),
                ('user_id_bonne', models.IntegerField(blank=True, null=True)),
                ('user_id_daycarecenter', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='baby_barcode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('identify', models.CharField(blank=True, max_length=1, null=True)),
                ('baby_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='baby_breastfeeding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('baby_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='baby_chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('identify', models.CharField(blank=True, max_length=1, null=True)),
                ('message', models.CharField(max_length=500)),
                ('user_id', models.IntegerField()),
                ('baby_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='baby_defecation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('baby_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='baby_dessertfruit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('baby_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='baby_diaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('baby_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='baby_grocery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('baby_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='baby_picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=baby_user.models.PathAndRename('image/baby_picture/'))),
                ('baby_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='baby_relatives',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('baby_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
