# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='care_record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('baby_id', models.IntegerField()),
                ('bonne_id', models.IntegerField()),
                ('sex', models.CharField(blank=True, default='-1', max_length=2, null=True)),
            ],
        ),
    ]
