# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='user_id_bonne',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baby',
            name='user_id_daycarecenter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baby',
            name='user_id_father',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baby',
            name='user_id_mother',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baby_barcode',
            name='baby_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='baby_breastfeeding',
            name='baby_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='baby_chat',
            name='baby_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='baby_chat',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='baby_defecation',
            name='baby_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='baby_dessertfruit',
            name='baby_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='baby_diaper',
            name='baby_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='baby_grocery',
            name='baby_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='baby_picture',
            name='baby_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='baby_relatives',
            name='baby_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='baby_relatives',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
