# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0002_care_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='care_record',
            name='center_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='care_record',
            name='bonne_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
