# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 13:07
from __future__ import unicode_literals

import baby_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0003_auto_20160316_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=baby_user.models.PathAndRename('image/baby/')),
        ),
        migrations.AlterField(
            model_name='baby_picture',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=baby_user.models.PathAndRename('image/baby_picture/')),
        ),
    ]
