# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0004_auto_20160317_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='sex',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
