# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 08:46
from __future__ import unicode_literals

import baby_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0005_auto_20160318_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='birthday',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='baby',
            name='height',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='baby',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to=baby_user.models.PathAndRename('image/baby/')),
        ),
        migrations.AlterField(
            model_name='baby',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='baby',
            name='nickname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='baby',
            name='sex',
            field=models.CharField(blank=True, default=0, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='baby',
            name='tips',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='baby',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='baby_breastfeeding',
            name='content',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='baby_defecation',
            name='content',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='baby_dessertfruit',
            name='content',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='baby_diaper',
            name='content',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='baby_grocery',
            name='content',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='baby_picture',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to=baby_user.models.PathAndRename('image/baby_picture/')),
        ),
    ]
